### ISSUE TITLE
chemistry argument default value

### ISSUE THREAD

**Issue by sralchemab** [BimberLab/cellhashR#145]
Hi there.

I noticed that you are using a default value for the `chemistry` argument of `10xV3`. However, you could be having 10X V3 for both 3' and 5' kits and they would be different. Now, because this argument is used on the `EstimateMultipletRate` function where depending whether it's one or the other it will assign a hardcoded value, could you tell me what should I be using for the `10X 5' v2 kit`?

Thanks in advance.

**Comment by bbimber** [comment]
@sralchemab: this value is not really used for anything of consequence. It goes into computing the theoretical doublet rate, see here: https://github.com/BimberLab/cellhashR/blob/73753b1d34a6ac292b95303adb818f758c4fafb4/R/Utils.R#L174. The only thing this value is used for is printing the theoretical doublet rate on a plot. Therefore you can put an incorrect chemistry and it should not impact the results.

I will think about how to best handle this. At minimum I will try to improve the docs. I also wonder if I could let the user pass a value for expected doublet rate, or NULL to ignore this.

**Comment by bbimber** [comment]
@sralchemab, I pushed updates to the docs today, and made sure the code will work with NULL passed for chemistry. 

The docs should elaborate, but this value is used in two ways. Fundamentally, it's used to calculate the theoretical doublet rate based on the number of cells. That value can be used to: 1) draw a horizontal dotted line on the summary plot, showing expected doublet rate (obviously lacking chemistry is not a major issue here), and 2) there is a feature to consensus calling that will triage  any algorithm that produces a doublet rate that is 3X the theoretical rate. We do this because a lot of my lab's data is run headlessly and we find that's a major mode of failure (i.e. some algorithm gets a threshold wrong and calls lots of doublets). If chemistry is NULL, this is not run. Also, this only applies if maxAllowableDoubletRate = 'auto' (see: https://github.com/BimberLab/cellhashR/blob/1bbbe5324b8d132cabebd0338a2c9536d851d899/R/CellHashing.R#L138)
